/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ec.edu.ups.vista;

import ec.edu.ups.controlador.ControladorDocente;
import ec.edu.ups.controlador.ControladorEstudiante;
import ec.edu.ups.controlador.ControladorRector;
import ec.edu.ups.modelo.Docente;
import ec.edu.ups.modelo.Estudiante;
import ec.edu.ups.modelo.Rector;
import static ec.edu.ups.vista.VntPrincipal.ruta;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.JOptionPane;

/**
 *
 * @author braya
 */
public class VntGestionarEstudiantes extends javax.swing.JInternalFrame {

    private ControladorDocente ctrlDocente;
    private ControladorEstudiante ctrlEstudiantep;
    private ControladorRector ctrlRector;
    
    public static String ruta = "C:\\Users\\braya\\OneDrive\\Documentos\\NetBeansProjects\\Examen_Interciclo\\registrarRector";
    public static String ruta2 = "C:\\Users\\braya\\OneDrive\\Documentos\\NetBeansProjects\\Examen_Interciclo\\registrarDocente";
    public static String ruta3 = "C:\\Users\\braya\\OneDrive\\Documentos\\NetBeansProjects\\Examen_Interciclo\\registrarEstudiante";
    /**
     * Creates new form VntGestionarDocentes
     *
     * @param ctrlDocente
     * @param ctrlEstudiantep
     * @param ctrlRector
     */
    public VntGestionarEstudiantes(ControladorDocente ctrlDocente, ControladorEstudiante ctrlEstudiantep, ControladorRector ctrlRector) {
        initComponents();
        this.ctrlDocente = ctrlDocente;
        this.ctrlEstudiantep = ctrlEstudiantep;
        this.ctrlRector = ctrlRector;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel4 = new javax.swing.JLabel();
        jCbxTipoNum = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        txtTelefono = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtCorreo = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtContrsenia = new javax.swing.JPasswordField();
        txtCedula = new javax.swing.JTextField();
        btnRegistrar = new javax.swing.JButton();
        txtNombre = new javax.swing.JTextField();
        btnCancelar = new javax.swing.JButton();
        txtApellido = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        txtCurso = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtEdad = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txtNombre1 = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jCbxTipoNum1 = new javax.swing.JComboBox<>();
        txtApellido1 = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        txtTelefono1 = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        txtCorreo1 = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        txtEdad1 = new javax.swing.JTextField();
        txtContrsenia1 = new javax.swing.JPasswordField();
        jLabel17 = new javax.swing.JLabel();
        txtCedula1 = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();

        setClosable(true);
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameActivated(evt);
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
            }
        });

        jLabel4.setText("Edad");

        jCbxTipoNum.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "*** Elija Tipo ***", "Casa", "Movil" }));
        jCbxTipoNum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCbxTipoNumActionPerformed(evt);
            }
        });

        jLabel5.setText("Telefono");

        txtTelefono.setText("287235 o 0909090909");
        txtTelefono.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txtTelefonoMousePressed(evt);
            }
        });

        jLabel6.setText("Correo");

        jLabel7.setText("Contraseña");

        txtCedula.setText("0101010101");
        txtCedula.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txtCedulaMousePressed(evt);
            }
        });

        btnRegistrar.setText("REGISTRAR");
        btnRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarActionPerformed(evt);
            }
        });

        btnCancelar.setText("CANCELAR");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        jLabel8.setText("Curso");

        jLabel1.setText("Cedula");

        jLabel2.setText("Nombre");

        jLabel3.setText("Apellido");

        jLabel9.setText("Tipo de telefono");

        jLabel10.setText("Edad Representante");

        jCbxTipoNum1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "*** Elija Tipo ***", "Casa", "Movil" }));
        jCbxTipoNum1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCbxTipoNum1ActionPerformed(evt);
            }
        });

        jLabel11.setText("Telefono Representante");

        txtTelefono1.setText("287235 o 0909090909");
        txtTelefono1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txtTelefono1MousePressed(evt);
            }
        });

        jLabel13.setText("Cedula Representante");

        jLabel14.setText("Correo Representante");

        jLabel15.setText("Nombre Representante");

        jLabel16.setText("Contraseña Representante");

        jLabel17.setText("Apellido Representante");

        txtCedula1.setText("0101010101");
        txtCedula1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txtCedula1MousePressed(evt);
            }
        });

        jLabel18.setText("Tipo de telefono");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7)
                            .addComponent(jLabel1)
                            .addComponent(jLabel4)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2)
                            .addComponent(jLabel8)
                            .addComponent(jLabel5)
                            .addComponent(jLabel9))
                        .addGap(87, 87, 87)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtTelefono, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jCbxTipoNum, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txtCedula, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtApellido, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtCurso, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtEdad, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(txtCorreo)
                                .addComponent(txtContrsenia, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(44, 44, 44)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel14)
                            .addComponent(jLabel16)
                            .addComponent(jLabel13)
                            .addComponent(jLabel10)
                            .addComponent(jLabel17)
                            .addComponent(jLabel15)
                            .addComponent(jLabel11)
                            .addComponent(jLabel18))
                        .addGap(35, 35, 35)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtTelefono1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jCbxTipoNum1, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txtCedula1, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtNombre1, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtApellido1, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtEdad1, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(txtCorreo1)
                                .addComponent(txtContrsenia1, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(280, 280, 280)
                        .addComponent(btnRegistrar)
                        .addGap(35, 35, 35)
                        .addComponent(btnCancelar)))
                .addContainerGap(89, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(txtCedula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(txtApellido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(txtCurso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(txtEdad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(jCbxTipoNum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(txtTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(txtCorreo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(txtContrsenia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel13)
                            .addComponent(txtCedula1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel15)
                            .addComponent(txtNombre1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel17)
                            .addComponent(txtApellido1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10)
                            .addComponent(txtEdad1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel18)
                            .addComponent(jCbxTipoNum1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel11)
                            .addComponent(txtTelefono1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel14)
                            .addComponent(txtCorreo1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel16)
                            .addComponent(txtContrsenia1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnRegistrar)
                    .addComponent(btnCancelar))
                .addGap(16, 16, 16))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jCbxTipoNumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCbxTipoNumActionPerformed
        // TODO add your handling code here:
        if (jCbxTipoNum.getSelectedIndex() > 0) {
            txtTelefono.setEditable(true);
        }
    }//GEN-LAST:event_jCbxTipoNumActionPerformed

    private void txtTelefonoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtTelefonoMousePressed
        // TODO add your handling code here:
        txtTelefono.setText("");
    }//GEN-LAST:event_txtTelefonoMousePressed

    private void txtCedulaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtCedulaMousePressed
        // TODO add your handling code here:
        txtCedula.setText("");
    }//GEN-LAST:event_txtCedulaMousePressed

    private void btnRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarActionPerformed
        // TODO add your handling code here:
        String cedula = txtCedula.getText();
        String nombre = txtNombre.getText();
        String apellido = txtApellido.getText();
        int edad = Integer.valueOf(txtEdad.getText());
        String correo = txtCorreo.getText();
        String contrasenia = txtContrsenia.getText();
        String cursoAsignado = txtCurso.getText();
        String telefono = txtTelefono.getText();
        int cbx = jCbxTipoNum.getSelectedIndex();
        ///
        String Recedula = txtCedula1.getText();
        String Renombre = txtNombre1.getText();
        String Reapellido = txtApellido1.getText();
        int Reedad = Integer.valueOf(txtEdad1.getText());
        String Recorreo = txtCorreo1.getText();
        String Recontrasenia = txtContrsenia1.getText();
        String Retelefono = txtTelefono1.getText();
        int Recbx = jCbxTipoNum1.getSelectedIndex();
        if (!cedula.isBlank() || !nombre.isBlank() || !apellido.isBlank() || !txtEdad.getText().isBlank() || !correo.isBlank() || !contrasenia.isBlank() || !cursoAsignado.isBlank() || !telefono.isBlank() || cbx > 0
                || !Recedula.isBlank() || !Renombre.isBlank() || !Reapellido.isBlank() || !txtEdad1.getText().isBlank() || !Recorreo.isBlank() || !Recontrasenia.isBlank() || !Retelefono.isBlank() || Recbx > 0) {
            if (telefono(telefono) && cedula(cedula) && telefono(Retelefono) && cedula(Recedula)) {
                
                if (ctrlEstudiantep.comprobarCorreo(correo) && ctrlEstudiantep.comprobarCorreo(Recorreo) && !listar(correo)) {
                    try {
                        try {
                            var estudiante = new Estudiante(Recedula, Renombre, Reapellido, Retelefono, Reedad, Recorreo, Recontrasenia, cursoAsignado, cedula, nombre, apellido, edad, telefono, correo, contrasenia);
                            ctrlEstudiantep.create(estudiante);
                            ctrlDocente.obtenerSesionInciada().createEstudiante(estudiante);
//                            ctrlRector.obtenerSesionInciada().createEstudiante(estudiante);
                            ctrlEstudiantep.guardardatos(ruta3);
                            ctrlDocente.guardardatos(ruta2);
                            System.out.println("**************************************\n"
                                    + ctrlEstudiantep.cargarDatos(ruta3));
                            JOptionPane.showMessageDialog(this, "Registrado correctamente");
                            limpiar();
                        } catch (FileNotFoundException | ClassNotFoundException ex) {
                            Logger.getLogger(VntGestionarEstudiantes.class.getName()).log(Level.SEVERE, null, ex);
                        }
                    } catch (IOException ex) {
                        Logger.getLogger(VntGestionarEstudiantes.class.getName()).log(Level.SEVERE, null, ex);
                    }
//                    this.dispose();
                } else {
                    JOptionPane.showMessageDialog(this, "Este correo ya fue usado");
                    if (!ctrlEstudiantep.comprobarCorreo(correo)) {
                        txtCorreo.setText("");
                    }else if (!ctrlEstudiantep.comprobarCorreo(Recorreo)){
                        txtCorreo1.setText("");
                    }
                }
            } else {
                if (!telefono(telefono) && !telefono(Retelefono)) {
                    txtTelefono.setText("");
                }
                if (!cedula(cedula) && !cedula(Recedula)) {
                    txtCedula.setText("");
                }
                JOptionPane.showMessageDialog(this, "Los datos de algun campo estan mal ingresados");
            }
        } else {
            JOptionPane.showMessageDialog(this, "Hay campos vacios por llenar");
        }
    }//GEN-LAST:event_btnRegistrarActionPerformed

    public void limpiar() {
//        txtCedula.setText("");
        txtNombre.setText("");
        txtApellido.setText("");
        txtEdad.setText("");
        txtCorreo.setText("");
        txtContrsenia.setText("");
        txtCurso.setText("");
//        txtTelefono.setText("");
        jCbxTipoNum.getItemAt(0);
        txtNombre1.setText("");
        txtApellido1.setText("");
        txtEdad1.setText("");
        txtCorreo1.setText("");
        txtContrsenia1.setText("");
//        txtTelefono.setText("");
        jCbxTipoNum1.getItemAt(0);
    }

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        // TODO add your handling code here:
        limpiar();
        this.dispose();
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void jCbxTipoNum1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCbxTipoNum1ActionPerformed
        // TODO add your handling code here:
        if (jCbxTipoNum1.getSelectedIndex() > 0) {
            txtTelefono1.setEditable(true);
        }
    }//GEN-LAST:event_jCbxTipoNum1ActionPerformed

    private void txtTelefono1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtTelefono1MousePressed
        // TODO add your handling code here:
        txtTelefono1.setText("");
    }//GEN-LAST:event_txtTelefono1MousePressed

    private void txtCedula1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtCedula1MousePressed
        // TODO add your handling code here:
        txtCedula1.setText("");
    }//GEN-LAST:event_txtCedula1MousePressed

    private void formInternalFrameActivated(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameActivated
        // TODO add your handling code here:
        txtTelefono.setEditable(false);
        txtTelefono1.setEditable(false);
        limpiar();
    }//GEN-LAST:event_formInternalFrameActivated

    public boolean telefono(String telefono) {
        if (jCbxTipoNum.getSelectedItem().equals("Casa")) {
            System.out.println("casa");
            Pattern tipo = Pattern.compile("^(4|2)?\\d{6}$");
            Matcher m = tipo.matcher(telefono);
            System.out.println(m.matches());
            return m.matches();
        } else if (jCbxTipoNum.getSelectedItem().equals("Movil")) {
            System.out.println("movil");
            Pattern tipo = Pattern.compile("^(09)?\\d{8,8}$");
            Matcher m = tipo.matcher(telefono);
            System.out.println(m.matches());
            return m.matches();
        }
        return false;
    }

    public boolean cedula(String numCedula) {
        Pattern p = Pattern.compile("\\d{10,10}");
        Matcher m = p.matcher(numCedula);
        return m.matches();
    }

    public boolean listar(String correo) {
        try {
            var listRector = ctrlRector.cargarDatos(ruta);
            var listDoc = ctrlDocente.cargarDatos(ruta2);
            for (int i = 0; i < listRector.size(); i++) {
                    var rector = listRector.get(i);
                for (int j = 0; j < listDoc.size(); j++) {
                    var docente = listDoc.get(j);
                    if (correo.equals(rector.getCorreo()) || correo.equals(docente.getCorreo())) {
                        return true;
                    }
                }
            }
        } catch (IOException | ClassNotFoundException ex) {
            Logger.getLogger(VntGestionarDocentes.class.getName()).log(Level.SEVERE, null, ex);
        }
        return false;
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnRegistrar;
    private javax.swing.JComboBox<String> jCbxTipoNum;
    private javax.swing.JComboBox<String> jCbxTipoNum1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField txtApellido;
    private javax.swing.JTextField txtApellido1;
    private javax.swing.JTextField txtCedula;
    private javax.swing.JTextField txtCedula1;
    private javax.swing.JPasswordField txtContrsenia;
    private javax.swing.JPasswordField txtContrsenia1;
    private javax.swing.JTextField txtCorreo;
    private javax.swing.JTextField txtCorreo1;
    private javax.swing.JTextField txtCurso;
    private javax.swing.JTextField txtEdad;
    private javax.swing.JTextField txtEdad1;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtNombre1;
    private javax.swing.JTextField txtTelefono;
    private javax.swing.JTextField txtTelefono1;
    // End of variables declaration//GEN-END:variables
}
