/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ec.edu.ups.vista;

//import ec.edu.ups.controlador.ControladorRector;
import ec.edu.ups.controlador.ControladorDocente;
import ec.edu.ups.modelo.Estudiante;
import java.io.BufferedReader;
import java.io.IOException;
import java.io.InputStream;
import java.io.InputStreamReader;
import java.net.MalformedURLException;
import java.net.URL;
import java.net.URLConnection;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;

/**
 *
 * @author braya
 */
public class VntGestionarActividades extends javax.swing.JInternalFrame {

    private ControladorDocente ctrlDocente;
    public static String ruta = "C:\\Users\\braya\\OneDrive\\Documentos\\NetBeansProjects\\Examen_Interciclo\\registrarEstudiante";

    /**
     * Creates new form VntGestionarActividades
     *
     * @param ctrlRector
     */
    public VntGestionarActividades(ControladorDocente ctrlDocente) {
        initComponents();
        this.ctrlDocente = ctrlDocente;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTextPane1 = new javax.swing.JTextPane();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtActividad = new javax.swing.JTextField();
        btnListar = new javax.swing.JButton();
        btnActividad = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jListNombres = new javax.swing.JList<>();
        jScrollPane4 = new javax.swing.JScrollPane();
        jListApellidos = new javax.swing.JList<>();
        jScrollPane5 = new javax.swing.JScrollPane();
        jListProgramas = new javax.swing.JList<>();

        jScrollPane1.setViewportView(jTextPane1);

        setClosable(true);
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameActivated(evt);
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
            }
        });

        jLabel2.setText("Listado de Estudiantes");

        jLabel3.setText("Ingrese Actividad");

        btnListar.setText("Listar");
        btnListar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnListarActionPerformed(evt);
            }
        });

        btnActividad.setText("Actividad");
        btnActividad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActividadActionPerformed(evt);
            }
        });

        jScrollPane2.setViewportView(jListNombres);

        jScrollPane4.setViewportView(jListApellidos);

        jScrollPane5.setViewportView(jListProgramas);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 50, Short.MAX_VALUE)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(49, 49, 49)
                        .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(43, 43, 43))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtActividad, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(48, 48, 48)
                                .addComponent(btnActividad))
                            .addComponent(btnListar))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtActividad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnActividad))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 60, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(btnListar))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(148, 148, 148))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jScrollPane5)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 221, Short.MAX_VALUE)
                            .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 221, Short.MAX_VALUE))
                        .addGap(39, 39, 39))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formInternalFrameActivated(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameActivated
        // TODO add your handling code here:
    }//GEN-LAST:event_formInternalFrameActivated

    private void btnListarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnListarActionPerformed
        // TODO add your handling code here:
        var listaEstudiante = ctrlDocente.obtenerSesionInciada().getListaEstudiantes();
//            mostrarLista(ctrlDocente.obtenerSesion().getListaEstudiantes());
        mostrarLista(listaEstudiante);
    }//GEN-LAST:event_btnListarActionPerformed

    private void btnActividadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActividadActionPerformed
        // TODO add your handling code here:
//        ctrlDocente.ingresarActividad("<a\\shref=\"(http(s)?\\:\\/\\/)");
        String textoabuscar = txtActividad.getText();
        StringBuilder stringBuilder = new StringBuilder();
        if (!textoabuscar.isBlank()) {
            ctrlDocente.ingresarActividad("<a\\shref=\"(http(s)?\\:\\/\\/)(www)?(.[^\"\\s])+");
            try {
                URL urlObject = new URL("https://www.google.com.ec/search?q=" + textoabuscar.replaceAll("\\s", "\\+"));
                URLConnection urlConnection = urlObject.openConnection();
                urlConnection.setRequestProperty("User-Agent", "Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.11 (KHTML, like Gecko) Chrome/23.0.1271.95 Safari/537.11");
                BufferedReader bufferedReader = new BufferedReader(new InputStreamReader(urlConnection.getInputStream(), "UTF-8"));
                String inputLine;
                while ((inputLine = bufferedReader.readLine()) != null) {
                    stringBuilder.append(inputLine);
                }
            } catch (IOException ex) {
                Logger.getLogger(VntGestionarActividades.class.getName()).log(Level.SEVERE, null, ex);
            }
            mostrarListaActividades(ctrlDocente.buscarCorpus(stringBuilder.toString()));
        } else {
            JOptionPane.showMessageDialog(this, "Campo vacio");
        }

//        System.out.println(stringBuilder.toString());
        List<String> actividadesBus = ctrlDocente.buscarCorpus(stringBuilder.toString());
        actividadesBus.stream().forEach(c -> System.out.println(c));

    }//GEN-LAST:event_btnActividadActionPerformed

    private void mostrarLista(List<Estudiante> rutaL) {
        DefaultListModel modeloNombres = new DefaultListModel();
        DefaultListModel modeloApellidos = new DefaultListModel();
        modeloApellidos.clear();
        modeloNombres.clear();
        for (var lista : rutaL) {
            modeloNombres.addElement(lista.getNombre());
        }
        for (var lista : rutaL) {
            modeloApellidos.addElement(lista.getApellido());
        }
        jListApellidos.setModel(modeloApellidos);
        jListNombres.setModel(modeloNombres);
        System.out.println("Nombres" + modeloNombres);
        System.out.println("Apellidos" + modeloApellidos);
    }

    private void mostrarListaActividades(List<String> listaActividades) {
        DefaultListModel modelo = new DefaultListModel();
        modelo.clear();
        for (var lista : listaActividades) {
            modelo.addElement(lista);
            System.out.println("actividades--> " + modelo.toString());
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnActividad;
    private javax.swing.JButton btnListar;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JList<String> jListApellidos;
    private javax.swing.JList<String> jListNombres;
    private javax.swing.JList<String> jListProgramas;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextPane jTextPane1;
    private javax.swing.JTextField txtActividad;
    // End of variables declaration//GEN-END:variables

    private void toString(InputStream inputStream) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
}
