/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ec.edu.ups.vista;

import ec.edu.ups.controlador.ControladorDocente;
import ec.edu.ups.controlador.ControladorEstudiante;
import ec.edu.ups.controlador.ControladorRector;
import javax.swing.JInternalFrame;
import javax.swing.JMenu;
import javax.swing.JMenuItem;

/**
 *
 * @author braya
 */
public class VntPrincipal extends javax.swing.JFrame {
    private VntRegistrar vntRegistar;
    private VntIniciarSesion vntIniciar;
    private VntGestionarDocentes vntGestionarDocente;
    private VntGestionarEstudiantes vntGestionarEstudiante;
    private VntGestionarActividades vntGestionasActividades;
    
    private ControladorRector ctrlRector;
    private ControladorDocente ctrlDocente;
    private ControladorEstudiante ctrlEstudiante; 
    
    public static String ruta = "C:\\Users\\braya\\OneDrive\\Documentos\\NetBeansProjects\\Examen_Interciclo\\registrarRector";
    public static String ruta2 = "C:\\Users\\braya\\OneDrive\\Documentos\\NetBeansProjects\\Examen_Interciclo\\registrarDocente";
    public static String ruta3 = "C:\\Users\\braya\\OneDrive\\Documentos\\NetBeansProjects\\Examen_Interciclo\\registrarEstudiante";
    /**
     * Creates new form VntPrincipal
     */
    public VntPrincipal() {
        initComponents();
        //
        ctrlRector = ControladorRector.getInstance();
        ctrlDocente = ControladorDocente.getInstance();
        ctrlEstudiante = new ControladorEstudiante();
        //
        vntRegistar = new VntRegistrar(ctrlRector);
        vntIniciar = new VntIniciarSesion(ctrlRector, ctrlDocente, this);
        vntGestionarDocente = new VntGestionarDocentes(ctrlDocente, ctrlRector);
        vntGestionarEstudiante = new VntGestionarEstudiantes(ctrlDocente, ctrlEstudiante, ctrlRector);
        vntGestionasActividades = new VntGestionarActividades(ctrlDocente);
        getGestionarMenu().setVisible(false);
        getAlumnosMenuItem().setVisible(false);
        getActividadesMenuItem().setVisible(false);
        getDocenteMenuItem().setVisible(false);
    }

    public JMenu getGestionarMenu() {
        return gestionarMenu;
    }

    public JMenuItem getAlumnosMenuItem() {
        return AlumnosMenuItem;
    }

    public JMenuItem getActividadesMenuItem() {
        return actividadesMenuItem;
    }

    public JMenuItem getDocenteMenuItem() {
        return docenteMenuItem;
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        desktopPane = new javax.swing.JDesktopPane();
        menuBar = new javax.swing.JMenuBar();
        Menu = new javax.swing.JMenu();
        registrarMenu = new javax.swing.JMenuItem();
        iniciarMenu = new javax.swing.JMenuItem();
        cerrarSesioMenuItem = new javax.swing.JMenuItem();
        salirMenu = new javax.swing.JMenuItem();
        gestionarMenu = new javax.swing.JMenu();
        docenteMenuItem = new javax.swing.JMenuItem();
        AlumnosMenuItem = new javax.swing.JMenuItem();
        actividadesMenuItem = new javax.swing.JMenuItem();
        helpMenu = new javax.swing.JMenu();
        contentMenuItem = new javax.swing.JMenuItem();
        aboutMenuItem = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Menu.setMnemonic('f');
        Menu.setText("Menu");

        registrarMenu.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_R, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        registrarMenu.setMnemonic('o');
        registrarMenu.setText("Registrar");
        registrarMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registrarMenuActionPerformed(evt);
            }
        });
        Menu.add(registrarMenu);

        iniciarMenu.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_I, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        iniciarMenu.setMnemonic('s');
        iniciarMenu.setText("Iniciar Sesion");
        iniciarMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                iniciarMenuActionPerformed(evt);
            }
        });
        Menu.add(iniciarMenu);

        cerrarSesioMenuItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_Q, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        cerrarSesioMenuItem.setText("Cerrar Sesion");
        cerrarSesioMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cerrarSesioMenuItemActionPerformed(evt);
            }
        });
        Menu.add(cerrarSesioMenuItem);

        salirMenu.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_ESCAPE, 0));
        salirMenu.setMnemonic('x');
        salirMenu.setText("Salir");
        salirMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salirMenuActionPerformed(evt);
            }
        });
        Menu.add(salirMenu);

        menuBar.add(Menu);

        gestionarMenu.setMnemonic('e');
        gestionarMenu.setText("Gestionar");

        docenteMenuItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_D, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        docenteMenuItem.setMnemonic('t');
        docenteMenuItem.setText("Docentes");
        docenteMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                docenteMenuItemActionPerformed(evt);
            }
        });
        gestionarMenu.add(docenteMenuItem);

        AlumnosMenuItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_E, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        AlumnosMenuItem.setMnemonic('y');
        AlumnosMenuItem.setText("Estudiantes");
        AlumnosMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AlumnosMenuItemActionPerformed(evt);
            }
        });
        gestionarMenu.add(AlumnosMenuItem);

        actividadesMenuItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_A, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        actividadesMenuItem.setMnemonic('d');
        actividadesMenuItem.setText("Actividades");
        actividadesMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                actividadesMenuItemActionPerformed(evt);
            }
        });
        gestionarMenu.add(actividadesMenuItem);

        menuBar.add(gestionarMenu);

        helpMenu.setMnemonic('h');
        helpMenu.setText("Help");

        contentMenuItem.setMnemonic('c');
        contentMenuItem.setText("Contents");
        helpMenu.add(contentMenuItem);

        aboutMenuItem.setMnemonic('a');
        aboutMenuItem.setText("About");
        helpMenu.add(aboutMenuItem);

        menuBar.add(helpMenu);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktopPane, javax.swing.GroupLayout.DEFAULT_SIZE, 900, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktopPane, javax.swing.GroupLayout.DEFAULT_SIZE, 600, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void salirMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salirMenuActionPerformed
        System.exit(0);
    }//GEN-LAST:event_salirMenuActionPerformed

    private void registrarMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registrarMenuActionPerformed
        // TODO add your handling code here:
        abrir(vntRegistar);
    }//GEN-LAST:event_registrarMenuActionPerformed

    private void iniciarMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_iniciarMenuActionPerformed
        // TODO add your handling code here:
        abrir(vntIniciar);
    }//GEN-LAST:event_iniciarMenuActionPerformed

    private void docenteMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_docenteMenuItemActionPerformed
        // TODO add your handling code here:
        abrir(vntGestionarDocente);
    }//GEN-LAST:event_docenteMenuItemActionPerformed

    private void AlumnosMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AlumnosMenuItemActionPerformed
        // TODO add your handling code here:
        abrir(vntGestionarEstudiante);
    }//GEN-LAST:event_AlumnosMenuItemActionPerformed

    private void actividadesMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_actividadesMenuItemActionPerformed
        // TODO add your handling code here:
        abrir(vntGestionasActividades);
    }//GEN-LAST:event_actividadesMenuItemActionPerformed

    private void cerrarSesioMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cerrarSesioMenuItemActionPerformed
        // TODO add your handling code here:
        getGestionarMenu().setVisible(false);
        getAlumnosMenuItem().setVisible(false);
        getActividadesMenuItem().setVisible(false);
        getDocenteMenuItem().setVisible(false);
    }//GEN-LAST:event_cerrarSesioMenuItemActionPerformed
    public void abrir(JInternalFrame frame){
        desktopPane.add(frame);
        frame.setVisible(true);
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VntPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VntPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VntPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VntPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VntPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem AlumnosMenuItem;
    private javax.swing.JMenu Menu;
    private javax.swing.JMenuItem aboutMenuItem;
    private javax.swing.JMenuItem actividadesMenuItem;
    private javax.swing.JMenuItem cerrarSesioMenuItem;
    private javax.swing.JMenuItem contentMenuItem;
    private javax.swing.JDesktopPane desktopPane;
    private javax.swing.JMenuItem docenteMenuItem;
    private javax.swing.JMenu gestionarMenu;
    private javax.swing.JMenu helpMenu;
    private javax.swing.JMenuItem iniciarMenu;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JMenuItem registrarMenu;
    private javax.swing.JMenuItem salirMenu;
    // End of variables declaration//GEN-END:variables

}
